# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "categories", :force => true do |t|
    t.column "group_id",     :integer, :default => 0
    t.column "name",         :string
    t.column "description",  :string
    t.column "photos_count", :integer, :default => 0
  end

  create_table "comments", :force => true do |t|
    t.column "title",     :string
    t.column "body",      :text
    t.column "photo_id",  :integer
    t.column "topic_id",  :integer
    t.column "user_id",   :integer
    t.column "create_at", :datetime
  end

  create_table "groups", :force => true do |t|
    t.column "title",                :string
    t.column "slogan",               :string
    t.column "description",          :text
    t.column "created_at",           :datetime, :default => '2010-07-07 17:58:03'
    t.column "updated_at",           :datetime, :default => '2010-07-07 17:58:03'
    t.column "admin_id",             :integer,  :default => 0
    t.column "users_counts",         :integer,  :default => 0
    t.column "announcements_counts", :integer,  :default => 0
    t.column "topics_counts",        :integer,  :default => 0
    t.column "photos_counts",        :integer,  :default => 0
    t.column "view_counts",          :integer,  :default => 0
    t.column "group_pic_url",        :string
  end

  create_table "messages", :force => true do |t|
    t.column "title",      :string
    t.column "body",       :text
    t.column "created_at", :datetime, :default => '2010-07-07 17:58:03'
    t.column "viewed_at",  :datetime, :default => '2010-07-07 17:58:03'
    t.column "ccer_id",    :integer,  :default => 0
    t.column "owner_id",   :integer,  :default => 0
    t.column "from_id",    :integer,  :default => 0
    t.column "viewed_it",  :integer,  :default => 0
    t.column "replyed_it", :integer,  :default => 0
    t.column "remote_ip",  :string
  end

  create_table "photos", :force => true do |t|
    t.column "group_id",       :integer,  :default => 0
    t.column "user_id",        :integer,  :default => 0
    t.column "view_counts",    :integer,  :default => 0
    t.column "created_at",     :datetime, :default => '2010-07-07 17:58:03'
    t.column "updated_at",     :datetime, :default => '2010-07-07 17:58:03'
    t.column "reply_counts",   :integer,  :default => 0
    t.column "flowers_counts", :integer,  :default => 0
    t.column "eggs_counts",    :integer,  :default => 0
    t.column "title",          :string
    t.column "category_id",    :integer,  :default => 0
    t.column "description",    :text
    t.column "url",            :string
    t.column "simple_path",    :string
    t.column "content_type",   :string
  end

  create_table "topics", :force => true do |t|
    t.column "title",        :string
    t.column "body",         :text
    t.column "created_at",   :datetime, :default => '2010-07-07 17:58:02'
    t.column "updated_at",   :datetime, :default => '2010-07-07 17:58:02'
    t.column "group_id",     :integer,  :default => 0
    t.column "user_id",      :integer,  :default => 0
    t.column "view_counts",  :integer,  :default => 0
    t.column "reply_counts", :integer,  :default => 0
    t.column "top_it",       :integer,  :default => 0
    t.column "anonymous",    :integer,  :default => 0
    t.column "remote_ip",    :string
  end

  create_table "user_groups", :force => true do |t|
    t.column "group_id",    :integer, :default => 0
    t.column "name",        :string
    t.column "description", :string
    t.column "users_count", :integer, :default => 0
  end

  create_table "users", :force => true do |t|
    t.column "login_name",    :string
    t.column "display_name",  :string
    t.column "hashed_pass",   :string
    t.column "email",         :string
    t.column "mobile",        :string
    t.column "address",       :string
    t.column "birthday",      :date
    t.column "sex",           :integer
    t.column "state",         :integer,  :default => 0
    t.column "pic_url",       :string
    t.column "personality",   :text
    t.column "im",            :string
    t.column "website",       :string,   :default => "http://"
    t.column "link_id",       :integer,  :default => 0
    t.column "user_group_id", :integer,  :default => 1
    t.column "group_id",      :integer,  :default => 0
    t.column "topic_count",   :integer,  :default => 0
    t.column "photo_count",   :integer,  :default => 0
    t.column "created_at",    :datetime, :default => '2010-07-07 17:58:02'
    t.column "updated_at",    :datetime, :default => '2010-07-07 17:58:02'
  end

end
